name: Build Release Action
on:
  push:
    branches: [ master ]

jobs:
  Build-Release:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
    - name: Checkout v3
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Godot Export
      uses: firebelley/godot-export@v4.1.0
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_export_templates.tpz
        relative_project_path: ./src/
        relative_export_path: ./export/
        archive_output: true

    - name: Update/Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest Release"
        files: |
          export/

